### ISSUE TITLE
Update launchpad URLs

### ISSUE THREAD

**Issue by vadi2** [IRE-Mudlet-Mapping/ire-mapping-script#10]
All of the launchpad URLs in https://github.com/IRE-Mudlet-Mapping/ire-mapping-script/blob/master/mudlet-mapper.xml need to be updated to something more proper.

**Comment by keneanung** [comment]
@vadi2: That reminds me... How will we get an update out to people after this was changed? I gather we need to push the changes to launchpad. Can you do this once this change got in?

**Comment by vadi2** [comment]
Yep.
