### ISSUE TITLE
goto <area> # doesn't work

### ISSUE THREAD

**Issue by vadi2** [IRE-Mudlet-Mapping/ire-mapping-script#100]
If 'goto <area>' brings up a menu with several options because of name ambiguity, clicking on any of the options doesn't work.

For example try `goto omni` in Starmourn` or `goto mhaldor` in Achaea.

**Comment by zacklucky7** [comment]
Can't replicate in Starmourn -- started at inkke station, did _goto omni_, chose option 1 'Omni Station', it autowalked through transfer stations and voidgates until I got there, then I tried moving around inside Omni and did it again, no issue

**Comment by keneanung** [comment]
Vadi2 means `goto Omni 1` for example

**Comment by jgh713** [comment]
Can't replicate either, also on 19.1.1 with Mudlet 3.15. Using both `goto omni 1` and `goto omni` followed by clicking an area works fine for me.

**Comment by jgh713** [comment]
Ha, actually. It's an issue with starmourn's game map. If you're using the default map, the "Omni Station" area is actually empty, and the omni station rooms are in unnamed area 8. There's no rooms in the area, so pathing fails silently.

**Comment by vadi2** [comment]
Aha... thanks for finding it :)

**Comment by Hevlikn** [comment]
I've fixed the roomless/unnamed areas in the crowdmap; can confirm both clicking and `goto <amb> <opt>` work

**Comment by keneanung** [comment]
This is fixed with the PR above.
