### ISSUE TITLE
showpath fails silently if a path can't be found(?)

### ISSUE THREAD

**Issue by zacklucky7** [IRE-Mudlet-Mapping/ire-mapping-script#104]
When trying to use the _showpath_ command, it appears to fail silently if a path can't be found.

Try _showpath 1320 1321_ -- a path is found and shown.
Try _showpath 1320 6544_ -- I know that you have to fly through space to get to this room, but showpath gives no feedback.

I'm assuming it's because it can't find a path. (these rooms were tested in Starmourn)

**Comment by keneanung** [comment]
I transferred this issue to the correct repository as it's a mapping script issue.
