### ISSUE TITLE
Speedwalk issues on latest release

### ISSUE THREAD

**Issue by siddister** [IRE-Mudlet-Mapping/ire-mapping-script#14]
I've noticed with the latest version available on the website (16.6.2) there seems to be a pathfinding issue. I'm not sure if it's with the mudlet getPath or this scripts mmp.getPath. I can't really isolate it.

What's happening is that it's not considering some of the temporary added special exits but is considering others. I can't isolate why this is, but for example, I have both the 'belt' and 'vernalcurio' configs activated. When going from outside the aetherplex (room 148) to Gaudiguch's nexus (11401) it should be using the belt and moving down (2 rooms, exits all line up) and instead is using the vernalcurio and taking a much longer path through the hearthstone. 

Both the special exits for these scripts are being added (and removed) as they should be, there is no cached path saved to override anything. I can't determine why it's choosing the one exit over the other one.

**Comment by jgh713** [comment]
https://ada-young.appspot.com/pastebin/ef4a6bfe

Similar issue. No idea why it's happening. Can't seem to pin it down, though mapper seems to refuse to use gallop at all.

**Comment by jgh713** [comment]
Issue resolved itself after nearly a week of nothing but this happening. Not sure when, or how, or why.

**Comment by vadi2** [comment]
Is this still an issue?

**Comment by taernae** [comment]
Can only confirm that I'm having no issues with gallop. (Lusternia also).
