### ISSUE TITLE
IRE moved all map.xml files to https, mudlet mapper ONLY looks for http address

### ISSUE THREAD

**Issue by JulesVladin** [IRE-Mudlet-Mapping/ire-mapping-script#18]
Please see full comments here:  

https://bugs.launchpad.net/mudlet/+bug/1427364

User "Chris" identifies the exact issue within the script here, in comment 11:

https://bugs.launchpad.net/mudlet/+bug/1427364/comments/11

That said, the issue is not with the downloaded file that I think is the main focus of this site, it's with a "backend" script that runs the mapper, so directly related, but... different, and possibly outside the scope of what people here are working on.  The problem is significant.  Even 3.0 delta users cannot download IRE's map.xml files, and since the mapper does not "see" map.xml files that the user might manually put into the appropriate spot in their profile, this means that the IRE maps are essentially invisible/inaccessible to all mudlet users until this issue is fixed.  Thanks for looking.

**Comment by SlySven** [comment]
I'm looking at the code for this at https://github.com/Mudlet/Mudlet/pull/326 for the development branch and will port it over to the 3.0 preview version if/when it gets adopted - note that following contact between @vadi2 and IRE (I think) it seems they have relented on the immediate need to use https to get the xml map files.

**Comment by jgh713** [comment]
The connection defaulted to https, but you could specify http in one of the get params and it would work from 2.1, you just had to change the url you were pulling from. Tecton hopped in and reverted the change, though.

**Comment by vadi2** [comment]
Issue was resolved I believe, no longer a problem.
