### ISSUE TITLE
Mapper updates automatically downloading

### ISSUE THREAD

**Issue by jgh713** [IRE-Mudlet-Mapping/ire-mapping-script#27]
If you're not on the latest version of the mapper, reconnecting to the game after a long disconnect forces a download of the mapper, and causes Mudlet to hang. This issue seems intermittent and I'm not at all sure what's causing it. ([unhelpful pastebin](https://ada-young.appspot.com/pastebin/llyNhlJT))

Not urgent, but definitely annoying as hell, and something to keep in mind when looking into other issues in case someone comes across this.

**Comment by QwindorRousseau** [comment]
I think this got corrected with a new mudlet version as I am not seeing it auto download a new map version on mudlet load.
