### ISSUE TITLE
Pierce the Veil - Achaea

### ISSUE THREAD

**Issue by CorenDuchai** [IRE-Mudlet-Mapping/ire-mapping-script#41]
mconfig option for dragons for pierce the veil
Syntax: PIERCE THE VEIL
Cooldown: 3.00 seconds of equilibrium
Resource: 500 mana
Arrival Room: 12695 (Dragonspire Mount.)
Takes 2.2 - 3 seconds to go through (so 4 seconds to account for people with slower connections)

Can be done from anywhere island wings work (duanatharic)

**Comment by QwindorRousseau** [comment]
Good to go with #60 merged.

**Comment by keneanung** [comment]
The mentioned PR is merged, so closing this.
