### ISSUE TITLE
goto not stopping once it gets to the area you wanted

### ISSUE THREAD

**Issue by QwindorRousseau** [IRE-Mudlet-Mapping/ire-mapping-script#47]
Goto is not stopping once you get to the area that you wanted to goto when you use wings. From what I can tell it's still going to the nearest room it calculated before it took wings exits into consideration and will path to that room nearest it calculated even if it was on the other side of the area when wings exit drops you off on the other side.

**Comment by PapaGuacamole** [comment]
I've picked up this  (don't know how to assign myself, I don't know git-fu!)

**Comment by QwindorRousseau** [comment]
Admin have the ability to assign people. Us contributor plebs don't have that ability. But #73 fixes this issue.
