### ISSUE TITLE
locateAndEchoSide

### ISSUE THREAD

**Issue by CorenDuchai** [IRE-Mudlet-Mapping/ire-mapping-script#62]
with the veil change in Achaea you now get the area when you farsee someone, that means you should be able to limit the 'found rooms' to be in the area it indicates. At the same time it should be possible to limit a room search to only be somewhere you can scry to anyway. It makes no sense to get a list of rooms on the planes/islands/Meropis/far north if you're sitting at prime and sensing somone via a non-veil farsee

**Comment by KaliLusternia** [comment]
the code side of that for farsee should have been done in #67 - the userdata still needs to be populated in the crowdmap for it to be fully functional, though.
