### ISSUE TITLE
Move crowdmap and mapping script to organisation

### ISSUE THREAD

**Issue by keneanung** [IRE-Mudlet-Mapping/ire-mapping-script#7]
@QwindorRousseau and I brainstormed a little more about the crowdmap and came up with an idea: GitHub now supports file uploads directly on the Gitub webpage. If an existing file is uploaded, it gets converted to a git change, so collaborators don't need to touch git at all (additionally there are no other maintainers than Qwindor right now).

With the help of GitHub pages, we can push the map file then over http to the users.

To consolidate everything mapper related, we created the organisation @IRE-Mudlet-Mapping, which curently has the new crowdmap repository.

And we would like to move the script over there too. It would also allow other people to accept merge requests and do updates.

**Comment by vadi2** [comment]
Sounds alright. Mudlet wiki would also need to be updated with any links
pointing here.

**Comment by keneanung** [comment]
Invited you to that org. I'll take care of the wiki links once the transferral is done.

**Comment by keneanung** [comment]
@vadi2 any ETA on when you can do the transferral?

**Comment by vadi2** [comment]
What's there to do? Just at the new remote and push to it in order to get
the code across.

**Comment by keneanung** [comment]
You can transfer the owenership of this repo. This has multiple pros:
- Forks get trasnferred
- Issues and PRs get transferred
- No "fork" status, so no confusion about what is the "main" repo
- as long as you don't re-fork the repository, links get forwarded to the new main repo

**Comment by vadi2** [comment]
OK, I'll look into this in the coming weekend when I get back.

**Comment by vadi2** [comment]
This has been done.

**Comment by vadi2** [comment]
I've updated links on the wiki page (http://wiki.mudlet.org/w/IRE_mapping_script), need someone to go through and update the link to launchpad in the script itself though #10.
